name: culture-ia
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core data science
  - pandas
  - requests
  - numpy<2.0.0
  - pyarrow=15.0.0
  - datasets=2.19.0
  # Vector DB & ML
  - faiss-cpu
  - sentence-transformers
  - transformers
  - tokenizers
  # Web Framework & Utils
  - fastapi
  - uvicorn
  - streamlit
  - python-dotenv
  # Dev tools
  - pytest
  - pytest-cov
  - pre-commit
  - black
  - pylint
  # LangChain Ecosystem & Dependencies
  - langchain
  - langchain-community
  - langchain-mistralai
  - langchain-huggingface
  - mistralai
  - ragas
  - tiktoken
